server:
  port: 8080
spring:
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: NY
  application:
    name: orderservice
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: 137162
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则
ribbon:
  eager-load:
    clients:
      -userservice # 指定饥饿加载服务名称
    enabled: true # 开启饥饿加载
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka

