server:
  port: 8090
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
      web-context-unify: false # 关闭 context 整合
      datasource: # 配置 Sentinel 的规则持久化
        flow:
          nacos:
            server-addr: localhost:8848
            dataId: orderservice-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: flow
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: NY
        # namespace: 62ea870d-3c52-4063-8274-b6ae8d2b39c1 # 命名空间 ID
  application:
    name: orderservice
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: 137162
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则
ribbon:
  eager-load:
    clients:
      -userservice # 指定饥饿加载服务名称
    enabled: true # 开启饥饿加载
feign:
  sentinel:
    enabled: true # 开启 Feign 对 Sentinel 的支持
  httpclient:
    enabled: true # 开启 Feign 对 httpClient 的支持
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 每个路径的最大连接数


