spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security?characterEncoding=utf8&useSSL=false
    username: root
    password: 137162
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
server:
  port: 8080