spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mycnblog?characterEncoding=utf8&useSSL=false
    username: root
    password: 137162 #如果要部署到云服务器这里密码要更改(没有密码则为空)
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 发送邮件配置
  mail:
    host: smtp.qq.com # 配置 smtp 服务器地址
    port: 587 # smtp 服务器的端口
    username: 3501597019@qq.com # 配置邮箱用户名(你的邮箱地址)
    password: soqepleivmtidafa # 配置申请到的授权码(刚让复制的授权码)
    default-encoding: UTF-8 # 配置邮件编码
    properties:
      mail:
        auth: true
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory # 配饰 SSL 加密工厂
    from: 3501597019@qq.com
    # 发送方邮件,配在 yml 中可方便更改,一定要用授权的邮箱,不然会报异常

mybatis:
  mapper-locations: classpath:mybatis/**Mapper.xml

