server:
  port: 10010 # 网关端口
spring:
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos 地址
    gateway:
      default-filters:
        - AddRequestHeader=origin,gateway
      routes: # 网关路由配置
        - id: user-service # 路由 id，需要保证唯一性
          uri: lb://userservice # 路由的目标地址 http 就是固定地址
          predicates: # 路由断言，判断请求是否符合路由规则
            - Path=/user/** # 按照路径匹配，只要以 /user/ 开头就符合要求
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
          filters:
            - AddRequestHeader=Truth, It is freaking awesome!!
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决 options 请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:8090"
            allowedMethods: # 允许的跨域 ajax 的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带 cookie
            maxAge: 360000 # 这次跨域检测的有效期



