spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mycnblog_plus?characterEncoding=utf8&useSSL=false
    username: root
    password: #如果要部署到云服务器这里密码要更改(没有密码则为空)
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.qq.com # 配置 smtp 服务器地址
    port: 587 # smtp 服务器端口
    username: 3501597019@qq.com # 发送方邮箱地址/一定要是授权的邮箱,不然会报异常
    password: soqepleivmtidafa # 配置申请到的授权码(刚让复制的授权码)
    default-encoding: UTF-8
    properties:
      mail:
        # 配置 SSL 加密工厂
        smtp:
          ssl:
            # 本地测试,先放开 ssl
            enable: false
            required: false



server:
  port: 9090


mybatis:
  mapper-locations: classpath:mybatis/**Mapper.xml

