spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mycnblog_plus?characterEncoding=utf8&useSSL=false
    username: root
    #如果要部署到云服务器这里密码要更改(没有密码则为空)
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 配置数据源类型
    type: com.zaxxer.hikari.HikariDataSource

  mail:
    # 配置 smtp 服务器地址
    host: smtp.qq.com
    # smtp 服务器端口
    port: 587
    # 发送方邮箱地址/一定要是授权的邮箱,不然会报异常
    username: 3501597019@qq.com
    # 配置申请到的授权码(刚让复制的授权码)
    password: soqepleivmtidafa
    default-encoding: UTF-8
    properties:
      mail:
        # 配置 SSL 加密工厂
        smtp:
          ssl:
            # 本地测试,先放开 ssl
            enable: false
            required: false

# SpringBoot 服务器端口
server:
  port: 9090

# Mybatis-plus 配置
mybatis-plus:
  # 配置 xml 文件的路径
  mapper-locations: mybatis/*.xml



