server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mycnblog?characterEncoding=utf8&useSSL=false
    username: root
    password: ARNy@137162
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  mail:
    host: smtp.qq.com
    port: 587
    username: 3501597019@qq.com
    password: soqepleivmtidafa
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: false
            required: false
mybatis-plus:
  mapper-locations: mybatis/*.xml



